name: flutter_ui_system

packages:
  - packages/**
  - apps/**
  - tools/**

command:
  bootstrap:
    environment:
      sdk: ">=3.4.0 <4.0.0"
      flutter: ">=3.24.0"

scripts:
  get: dart run melos bootstrap
  analyze: dart run melos exec -- flutter analyze
  test: dart run melos exec --dir-exists=test -- flutter test
  test:goldens: dart run melos exec --scope=flutter_ui -- flutter test test/goldens
  test:update-goldens: dart run melos exec --scope=flutter_ui -- flutter test test/goldens --update-goldens
  format: dart run melos exec -- dart format .
  format:check: dart run melos exec -- dart format --output=none --set-exit-if-changed .
  clean: dart run melos exec -- flutter clean
  publish:dry-run:flutter: dart run melos exec --scope=flutter_ui_tokens --scope=flutter_ui_utils --scope=flutter_ui -- flutter pub publish --dry-run
  publish:dry-run:cli: dart run melos exec --scope=flutter_ui_cli -- dart pub publish --dry-run
